### PR TITLE
Implementing bash-history command for tockOS

### PR DESCRIPTION
**Pull request by mihai-negru**
### Pull Request Overview

This pull request implements a bash-history for tockOS

### Testing Strategy

This pull reuqest is and will be tested on a nordic nrf52840dk board

### TODO or Help Wanted

This pull request is still in development, it needs help on modifying the ProcessConsole Structure

### Documentation Updated

No documentation updated

### CODE REVIEW

**Comment by alexandruradovici** [comment]
@CosminGGeorgescu has a working implementation, but with arrays instead of data types. Can you please work together to merge these two PRs?

**Comment by alexandruradovici** [comment]
You can both chat using https://gitter.im/UPB-CS-OpenSourceUpstream/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by mihai-negru** [comment]
> @CosminGGeorgescu has a working implementation, but with arrays instead of data types. Can you please work together to merge these two PRs? 

Sure, I will try to make the changes

**Comment by mihai-negru** [comment]
Hi, should we close this pull request?

**Comment by alexandruradovici** [comment]
Yes.

**Pull request closed without merging**
