### PR TITLE
Refactoring get_peripherals

### PR DESCRIPTION
**Pull request by RaresCon**
### Pull Request Overview

This pull request refactors all appearances of the `get_peripherals()` function to `create_peripherals()`.
Issue: https://github.com/tock/tock/issues/3270

### Testing Strategy

This pull request was not tested being only refactoring.

### TODO or Help Wanted

This pull request still needs feedback / code review.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by alexandruradovici** [comment]
This looks good, please rebase it to the newest master. @RaresCon

**Comment by RaresCon** [comment]
I'm sorry for replying so late, I had some problems regarding the way of rebasing my fork. So, in short, my repo is forked from the original Tock repo, so I can't really rebase to the newest master of this one. I tried some dark magic in the past days, but couldn't remove the commits coming from the origin. So I wanted to ask, may I reopen this PR after forking it from here with the same changes? The reason for forking the original one is that I wanted to have access to the newest tree, so I can see if some issues are still active.

**Comment by alexandruradovici** [comment]
Looks good, please send the PR to upstream and place a link to it here.

**Comment by alexandruradovici** [comment]
Please rebase it to the Tock master and force-push it here.

**Comment by alexandruradovici** [comment]
Send it to upstream and post a link.

**Review by alexandruradovici — APPROVED** [review]

**Comment by RaresCon** [comment]
https://github.com/tock/tock/pull/3385

**Pull request closed without merging**
